name: linux
on: [push, pull_request]

jobs:
  centos7:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        COMPILER: [gcc10, clang11]
        LCG: [100]
        include:
          - COMPILER: gcc8
            LCG: 99python2

    steps:
    - uses: actions/checkout@v2
    - uses: cvmfs-contrib/github-action-cvmfs@v3
    - uses: aidasoft/run-lcg-view@v4
      with:
        view-path: "/cvmfs/clicdp.cern.ch/iLCSoft/lcg/${{ matrix.LCG }}/nightly/x86_64-centos7-${{ matrix.COMPILER }}-opt"
        setup-script: "init_ilcsoft.sh"
        run: |
          mkdir build
          cd build
          cmake -GNinja -C ${ILCSOFT}/ILCSoft.cmake -DCMAKE_CXX_FLAGS=" -fdiagnostics-color=always " -DINSTALL_DOC=ON -DUSE_EXTERNAL_CATCH2=OFF ..
          ninja -k0
          ctest --output-on-failure
          ninja install
